name: nexora_app
description: Nexora Finance - Modern Personal Finance App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^16.3.0

  # Networking
  dio: ^5.11.0

  # Local Database
  sqflite: ^2.4.3
  path_provider: ^2.1.6

  # Local Storage
  shared_preferences: ^2.5.3

  # UI
  flutter_svg: ^2.2.1
  lottie: ^3.3.2
  fl_chart: ^1.2.0
  google_fonts: ^6.3.0
  gap: ^3.0.1

  # Utils
  intl: ^0.20.3
  equatable: ^2.0.7

  # JSON
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700

    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
